language: python
python:
  - "3.9"

script:
- pytest
- cd docs/ && make clean && make html && touch _build/html/.nojekyll && cd ..

after_success:
  - coveralls

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/_build/html
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: vc2
